package bd_mysql;

import javax.swing.table.DefaultTableModel;
import util.Configuracion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Ventana_Provedores extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Provedores
     */
    public Ventana_Provedores() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProveedores = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proveedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 547, -1));

        jtProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jtProveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 527, 140));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar cliente.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.jpg"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 57, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 51, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.jpg"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 50, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo 1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      Configuracion.titulo = "Agregar Proveedor";
      Configuracion.accion = 1;
      new GestionProveedor (this,true);
      mostrarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      seleccionar_fila();
      if ( Configuracion.id.length() > 0){
      Configuracion.titulo = "Editar Proveedor";
      Configuracion.accion = 2;
      new GestionProveedor (this,true);
      mostrarTabla();
       }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      seleccionar_fila();
      if ( Configuracion.id.length() > 0){
      Configuracion.titulo = "Eliminar Proveedor";
      Configuracion.accion = 3;
      new GestionProveedor (this,true);
      mostrarTabla();
      }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose(); 
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void seleccionar_fila(){
        int fila = -1;
        Configuracion.id = "";
        if (jtProveedores.getSelectedRowCount() == 1)
            fila = jtProveedores.getSelectedRow();
        else 
            JOptionPane.showMessageDialog(this, "Selecciona Solo Un Elemento", "Error", JOptionPane.ERROR_MESSAGE);
        if (fila > -1)
            Configuracion.id = (String)jtProveedores.getValueAt(fila, 1);
        
        
    }
    private void mostrarTabla(){
        String[] titulos = {"#","Codigo","Nombre","Direccion","Telefono"};
        DefaultTableModel tabla= new DefaultTableModel ();
        ResultSet rs = ControlProveedor.mostrar();
        int x = 0;
        
          try {
            int nf = ControlProveedor.getRows();
            Object [][] filas = new String[nf][5]; 
            while(rs.next()){
                filas[x] [0] = (x + 1) + "";
                filas[x] [1] = rs.getString("codigo") + "";
                filas[x] [2] = rs.getString("nombre");
                filas[x] [3] = rs.getString("direccion");
                filas[x] [4] = rs.getString("telefono") + "";
                x++;
            }
            tabla.setDataVector(filas, titulos);
            jtProveedores.setModel(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(Ventana_Provedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
        
        
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtProveedores;
    // End of variables declaration//GEN-END:variables
}
