/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_mysql;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import util.Configuracion;

/**
 *
 * @author wilberto david
 */
public class Ventana_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Producto
     */
    public Ventana_Producto() {
        initComponents();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eqProduto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtProducto = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setTitle("Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eqProduto.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        eqProduto.setForeground(new java.awt.Color(102, 255, 204));
        eqProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqProduto.setText("Productos");
        jPanel1.add(eqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 10, 470, -1));

        JtProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Categoria", "Precio"
            }
        ));
        jScrollPane1.setViewportView(JtProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 121));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarProducto.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 50));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.jpg"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 55, 51));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 53, 51));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.jpg"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 54, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo 1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Configuracion.titulo = "Agregar producto";
        Configuracion.accion = 1;
        new GestionProductos(this, true);
        mostrarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        seleccionarFila();
        
        if(Configuracion.id.length()>0){
        Configuracion.titulo = "Editar producto";
        Configuracion.accion = 2;
        new GestionProductos(this, true);
        mostrarTabla();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        seleccionarFila();
        
        if(Configuracion.id.length()>0){
        Configuracion.titulo = "Eliminar Producto";
        Configuracion.accion = 3;
        new GestionProductos(this, true);
        mostrarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void seleccionarFila(){
        int fila = -1;
        Configuracion.id = "";
        
        if(JtProducto.getSelectedRowCount() == 1)
            fila = JtProducto.getSelectedRow();
        else
            JOptionPane.showMessageDialog(this, "Selecionar solo una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        if(fila>-1)
            Configuracion.id = (String)JtProducto.getValueAt(fila,1);
        
        System.out.println(Configuracion.id);
    }
    
    private void mostrarTabla(){
        String[] titulos = {"#", "Codigo", "Nombre", "Cantidad", "Precio", "Categoria"};
        DefaultTableModel tabla = new DefaultTableModel();
        ResultSet rs = Control_Producto.mostrar();
        int x=0;
             
        try {
            int nf = Control_Producto.getRows();
            Object[][] filas = new String[nf][6];
            
            while(rs.next()){
                filas[x][0] = (x+1) + "";
                filas[x][1] = rs.getString("Codigo");
                filas[x][2] = rs.getString("Nombre");
                filas[x][3] = rs.getInt("Cantidad") + "";
                filas[x][4] = rs.getDouble("Precio") + "";
                filas[x][5] = rs.getString("Categoria");
                x++;
            }
            tabla.setDataVector(filas, titulos);
            JtProducto.setModel(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(Ventana_Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtProducto;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel eqProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
